name: Actions Workflows

on:
  push:
    branches:
      - "master"



jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Copy swagger
        run: cp $1 $2 $3
        with:
          source: "./swagger.json"
          target: "./openapi.json"