name: Actions Workflows

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      # - name: Checkout current
      #   uses: actions/checkout@v3
      #   with:
      #     path: master

      - name: Current
        run: |
          pwd
          ls -al

      - name: Checkout remoted
        uses: actions/checkout@v3
        with:
          repository: liranAtli/github-actions
          path: github-actions


      - name: Remoted
        run: |
          pwd
          ls -al
      # - name: Create curl
      #   run: |
      #     curl --request GET \
      #     --url https://gw.yad2.io/my-ads/api-docs/swagger.json \
      #     --header 'content-type: application/json' \
      #     --fail
      # - name: Check out my other private repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: liranAtli/github-actions
      #     token: ${{ github.token }}
      #     ref: ${{ github.event.id }}
      # - name: copy file from current repo
      #   run: |
      #     echo ${{ github.event.id }}
      #     ls -al
      #     git config --global user.email "my-liran@bot.com"
      #     git config --global user.name "my-liran"
      #     git add -A
      #     git commit -m "random file"
      #     git push
# pull created -> pushed to master -> copy file -> checkout to new repo and new branch -> paste the file -> open new issue
