name: Actions Workflows

on:
  push:
    branches:
      - "master"

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "List files"
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          echo "${{ secrets.API_TOKEN_GITHUB }}"
