name: Actions Workflows

on:
  push:
    branches:
      - "master"

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "./swagger.json"
          destination_repo: "liranAtli/github-actions"
          destination_folder: "test-dir"
          user_email: "liranatli@email.com"
          user_name: "liranAtli"
          commit_message: "A custom message for the commit"
