name: Actions Workflows

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: PUSH FILE
        run: |
          pwd
          ls -a
          git clone git@github.com:liranAtli/github-actions.git"
          git config --global user.email "my-liran@bot.com"
          git config --global user.name "my-liran"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          ls -al
          cp ./swagger.json >> openapi.json
          ls -a
          git add -A
          git commit -m "random file"
          git push

# pull created -> pushed to master -> copy file -> checkout to new repo and new branch -> paste the file -> open new issue
